// Explicit publication inventory. Never discover private or admin files by glob.
export const pages = [
  ["index", "Home"],
  ["how-it-works", "How it works"],
  ["docs", "Documentation"],
  ["beta-install", "Beta setup"],
  ["pricing", "Plans"],
  ["privacy", "Privacy"],
  ["support", "Support"],
  ["404", "Page not found"],
];
export const documents = [
  [
    "USER_GUIDE.md",
    "user-guide",
    "User guide",
    "Using ROVER",
    "Start here: save, arrange, restore, and protect your workspaces.",
  ],
  [
    "HOW_IT_WORKS.md",
    "how-it-works",
    "How ROVER works",
    "Using ROVER",
    "Understand what the extension does and the tools behind it.",
  ],
  [
    "IMPORTING.md",
    "importing",
    "Import and export",
    "Using ROVER",
    "Move workspaces with copy, replacement, and merge previews.",
  ],
  [
    "LOCAL_BACKUP.md",
    "local-backup",
    "Full local backup",
    "Using ROVER",
    "Protect collections, favorites, appearance, templates, and revisions.",
  ],
  [
    "APPEARANCE.md",
    "appearance",
    "Appearance",
    "Using ROVER",
    "Styles, themes, accents, and browser limitations.",
  ],
  [
    "SUPPORT.md",
    "support",
    "Support guidance",
    "Using ROVER",
    "Troubleshoot and report a problem without sharing private data.",
  ],
  [
    "STATUS.md",
    "status",
    "Feature status",
    "Development and beta",
    "See what is local, tested, staged, or still waiting for setup.",
  ],
  [
    "ROADMAP.md",
    "roadmap",
    "Roadmap",
    "Development and beta",
    "Future improvements and release gates.",
  ],
  [
    "CHANGELOG.md",
    "changelog",
    "Change history",
    "Development and beta",
    "Completed development milestones and release notes.",
  ],
  [
    "RELEASING.md",
    "releasing",
    "Release process",
    "Development and beta",
    "Packages, build records, browser testing, and recovery.",
  ],
  [
    "BETA_SETUP_CHECKLIST.md",
    "beta-setup",
    "Beta setup checklist",
    "Development and beta",
    "Owner setup for testers, providers, and protected administration.",
  ],
  [
    "IDENTITY_SIGNIN.md",
    "identity-signin",
    "Account sign-in design",
    "Plans and policies",
    "Planned Google and Microsoft identity and profile separation.",
  ],
  [
    "HOSTED_SYNC.md",
    "hosted-sync",
    "Hosted sync design",
    "Plans and policies",
    "Staging evidence and the remaining cloud integration gates.",
  ],
  [
    "PRICING.md",
    "pricing",
    "Plans and trial details",
    "Plans and policies",
    "Free, the local trial, and proposed subscription plans.",
  ],
  [
    "TERMS.md",
    "terms",
    "Draft subscription terms",
    "Plans and policies",
    "Pre-release commercial terms; no active purchase offer.",
  ],
  [
    "PRIVACY.md",
    "privacy",
    "Privacy and data handling",
    "Plans and policies",
    "Local records, permissions, retention, exports, and deletion.",
  ],
  [
    "LICENSE.md",
    "license",
    "License statement",
    "Plans and policies",
    "Product rights and ownership of your workspace data.",
  ],
  [
    "ABOUT.md",
    "about",
    "About ROVER",
    "Project reference",
    "Product ownership, domains, and development boundaries.",
  ],
  [
    "BRAND_GUIDELINES.md",
    "brand-guidelines",
    "Brand guidelines",
    "Project reference",
    "One logo, acronym, palette, and voice across app and web.",
  ],
  [
    "HOSTING.md",
    "hosting",
    "Hosting plan",
    "Project reference",
    "The website, account service, and private admin boundaries.",
  ],
  [
    "ADMIN_PORTAL.md",
    "admin-portal",
    "Admin portal design",
    "Project reference",
    "Public design notes; the administration application is not deployed.",
  ],
  [
    "STORE_LISTING.md",
    "store-listing",
    "Store listing preparation",
    "Project reference",
    "Draft descriptions, permission explanations, and reviewer steps.",
  ],
  [
    "STORE_POLICY_REVIEW.md",
    "store-policy-review",
    "Store policy review",
    "Project reference",
    "Recorded policy research to recheck before store submission.",
  ],
  [
    "SITE_DEVELOPMENT.md",
    "site-development",
    "Website maintenance",
    "Project reference",
    "How documentation becomes branded pages and stays current.",
  ],
  [
    "README.md",
    "project-overview",
    "Project overview",
    "Project reference",
    "Public repository overview and documentation index.",
  ],
].map(([source, slug, title, group, description]) => ({
  source,
  slug,
  title,
  group,
  description,
}));
export const groups = [...new Set(documents.map((doc) => doc.group))];
export const documentUrl = (doc) => `/docs/${doc.slug}.html`;
export const sourceUrl = (source) =>
  `https://github.com/Chaotic-Reality/rover-workspaces-docs/blob/main/${source}`;
export const pageUrl = (id) => (id === "index" ? "/" : `/${id}.html`);
